language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../3817061_Silenko_AllLabi
  - make -j
  - ./VectorTest/VectorTest
  - ./MatrixTest/MatrixTest
  - ./StackTest/StackTest
notifications:
  email: false
