language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../3817061_Silenko_AllLabi
  - make -j
  - ./Vector/Vector
  - ./VectorTest/VectorTest
  -./Matrix/Matrix
  -./MatrixTest/MatrixTest
notifications:
  email: false
