language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../3817061_Silenko_AllLabi
  - make -j
  - ./VectorTest/VectorTest
  - ./MatrixTest/MatrixTest
  - ./StackTest/StackTest
  - ./QueueTest/QueueTest
  - ./ListTest/ListTest
  - ./ArrListTest/ArrListTest
  - ./MultiStackTest/MultiStackTest
  - ./PolynomialTest/PolynomialTest
  - ./StackListTest/StackListTest
  - ./PolishTest/PolishTest
  - ./ViewingTableTest/ViewingTableTest
  - ./SortTableTest/SortTableTest
  - ./PlexTest/PlexTest
notifications:
  email: false
